/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_011c131f (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/mpcpvnofauspjbazfaxx/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  
  if (!url || !key) {
    console.error("Missing Supabase credentials:", { 
      hasUrl: !!url, 
      hasKey: !!key 
    });
    throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY environment variables");
  }
  
  return createClient(url, key);
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_011c131f").upsert({
      key,
      value
    });
    if (error) {
      console.error("KV Set error:", error);
      throw new Error(error.message);
    }
  } catch (error) {
    console.error("KV Set failed:", error);
    throw error;
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_011c131f").select("value").eq("key", key).maybeSingle();
    if (error) {
      console.error("KV Get error:", error);
      throw new Error(error.message);
    }
    return data?.value;
  } catch (error) {
    console.error("KV Get failed:", error);
    throw error;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_011c131f").delete().eq("key", key);
    if (error) {
      console.error("KV Del error:", error);
      throw new Error(error.message);
    }
  } catch (error) {
    console.error("KV Del failed:", error);
    throw error;
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_011c131f").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
    if (error) {
      console.error("KV MSet error:", error);
      throw new Error(error.message);
    }
  } catch (error) {
    console.error("KV MSet failed:", error);
    throw error;
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_011c131f").select("value").in("key", keys);
    if (error) {
      console.error("KV MGet error:", error);
      throw new Error(error.message);
    }
    return data?.map((d) => d.value) ?? [];
  } catch (error) {
    console.error("KV MGet failed:", error);
    throw error;
  }
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_011c131f").delete().in("key", keys);
    if (error) {
      console.error("KV MDel error:", error);
      throw new Error(error.message);
    }
  } catch (error) {
    console.error("KV MDel failed:", error);
    throw error;
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_011c131f").select("key, value").like("key", prefix + "%");
    if (error) {
      console.error("KV GetByPrefix error:", error);
      throw new Error(error.message);
    }
    return data?.map((d) => d.value) ?? [];
  } catch (error) {
    console.error("KV GetByPrefix failed:", error);
    throw error;
  }
};